# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Rahman Kadierding
tagline:          'Welcome!'
description:      'Blog and homepage of Rahman Kadierding. I am finishing up my undergrad degree in a month, yey!'
url:              http://snklee.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/snklee/snklee.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
